# Generated by Django 5.0.4 on 2024-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.IntegerField(primary_key=int, serialize=False)),
                ('file', models.FileField(upload_to='./dir')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=256)),
            ],
        ),
    ]
