# Generated by Django 5.0.6 on 2024-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.IntegerField(primary_key=int, serialize=False)),
                ('ip', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=256)),
                ('new_file', models.FileField(upload_to='')),
            ],
        ),
    ]
