FROM python:3.11

RUN mkdir -p ./app
WORKDIR ./app

COPY ./requirements.txt ./

RUN python -m pip install --upgrade pip

RUN pip install -r ./requirements.txt

COPY ./ ./app

CMD [ "python", "./app/manage.py", "runserver", "0.0.0.0:8000" ]