# Generated by Django 5.0.4 on 2024-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatModel',
            fields=[
                ('id', models.IntegerField(primary_key=int, serialize=False)),
                ('fromF', models.CharField(max_length=255)),
                ('toF', models.CharField(max_length=255)),
            ],
        ),
    ]
